name: "Pre commit hook check"

on:
    pull_request:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    pre-commit-hook:
        name: Pre commit hook check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install dependencies
              run: npm i

            - name: Create empty commit
              run: git -c user.name='test' -c user.email='test@example.com' commit -m 'init for pr action' --allow-empty

            - name: Run pre-commit hook
              run: ./hooks/pre-commit.sh
